---
# @tag docker-container-prereq-all:description: Ensure all pre-requisites are installed
# @tag docker-container-prereq-traefik:description: Ensure all pre-requisites for Traefik are installed
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/prereq.yml"
  tags:
    - docker-container-prereq-all
    - docker-container-prereq-traefik

# @tag docker-container-restore-all:description: Run restic restore for all restic enabled containers.
# @tag docker-container-restore-traefik:description: Run restic restore for Traefik if restic is enabled.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/restore.yml"
  tags:
    - never
    - docker-container-restore-all
    - docker-container-restore-traefik
  when:
    - docker_container_traefik_restic_enable

# @tag docker-container-setup-all:description: Run setup task for all containers.
# @tag docker-container-setup-traefik:description: Run setup task for Traefik.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/setup.yml"
  tags:
    - docker-container-setup-all
    - docker-container-setup-traefik
    - docker-container-restore-all
    - docker-container-restore-traefik

# @tag docker-container-backup-init-all:description: Run init backup task for all container.
# @tag docker-container-backup-init-traefik:description: Run init backup task for Traefik if restic is enabled.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/backup_init.yml"
  tags:
    - docker-container-setup-all
    - docker-container-setup-traefik
    - docker-container-backup-init-all
    - docker-container-backup-init-traefik
  when:
    - docker_container_traefik_restic_enable

# @tag docker-container-remove-all:description: Remove all containers.
# @tag docker-container-remove-traefik:description: Remove Traefik.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/remove.yml"
  tags:
    - never
    - docker-container-remove-all
    - docker-container-remove-traefik
    - docker-container-purge-all
    - docker-container-purge-traefik

# @tag docker-container-purge-all:description: Remove all containers and delete volume mounts.
# @tag docker-container-purge-traefik:description: Remove Traefik and delete volume mounts.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/purge.yml"
  tags:
    - never
    - docker-container-purge-all
    - docker-container-purge-traefik


# @tag docker-container-backup-all:description: Backup all containers' volume mounts.
# @tag docker-container-backup-traefik:description: Backup Traefik volume mounts.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/backup.yml"
  tags:
    - never
    - docker-container-backup-all
    - docker-container-backup-traefik
  when:
    - docker_container_traefik_restic_enable

# @tag docker-container-backup-list-all:description: List all containers' backups.
# @tag docker-container-backup-list-traefik:description: List Traefik backups.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/backup_list.yml"
  tags:
    - never
    - docker-container-backup-list-all
    - docker-container-backup-list-traefik
  when:
    - docker_container_traefik_restic_enable
