---
- name: remove_files {{ docker_container_traefik_volume_dir }}
  file:
    path: "{{ docker_container_traefik_volume_dir }}"
    state: absent
  when: docker_container_traefik_volume_dir is defined
