---
# tasks file for ansible-role-docker-container-traefik

- name: docker_container - {{ docker_container_traefik_volume_dir }}
  ansible.builtin.file:
    path: "{{ docker_container_traefik_volume_dir }}/{{ item }}"
    state: directory
  loop:
    - "config"
    - "certs"

- name: docker_container {{ docker_container_traefik_name }} - static certs 
  ansible.builtin.copy:
    src: '{{ item.cert_file }}'
    dest: '{{ docker_container_traefik_volume_dir }}/certs/{{ item.cert_file | basename }}'
  loop: '{{ docker_container_traefik_static_certificates }}'
  when: 
    - docker_container_traefik_static_certificates is defined
    - docker_container_traefik_static_certificates | length > 0

- name: docker_container {{ docker_container_traefik_name }} - static cert keys
  ansible.builtin.copy:
    src: '{{ item.key_file }}'
    dest: '{{ docker_container_traefik_volume_dir }}/certs/{{ item.key_file | basename }}'
    mode: "0600"
  loop: '{{ docker_container_traefik_static_certificates }}'
  when: 
    - docker_container_traefik_static_certificates is defined
    - docker_container_traefik_static_certificates | length > 0

- name: docker_container {{ docker_container_traefik_name }} - traefik.providers.file.toml
  ansible.builtin.template:
    src: "{{ docker_container_traefik_provider_config_template }}"
    dest: "{{ docker_container_traefik_volume_dir }}/config/traefik.providers.file.toml"

- name: docker_image pull {{ docker_image_traefik_name }}
  community.docker.docker_image:
    name: '{{ docker_image_traefik_name }}'
    source: pull
    # Select platform for pulling. If not specified, will pull whatever docker prefers.
    pull:
      platform: amd64
  when: 
    - docker_image_traefik_pull

- name: docker_network {{ docker_container_traefik_name }}
  community.docker.docker_network:
    ipam_config: "{{ docker_network_traefik_ipam_config | default(omit) }}"
    name: "{{ docker_network_traefik_name }}"
    driver: "{{ docker_network_traefik_driver | default('bridge') }}"
    attachable: "{{ docker_network_traefik_attachable | default(true) }}"
    enable_ipv6: "{{ docker_network_traefik_enable_ipv6 | default(false) }}"
    internal: "{{ docker_network_traefik_internal | default(false) }}"
    state: present


- name: docker_container {{ docker_container_traefik_name }}
  community.docker.docker_container:
    name: "{{ docker_container_traefik_name }}"
    image: "{{ docker_container_traefik_image }}"
    comparisons: "{{ docker_container_traefik_comparisons }}"
    state: "{{ docker_container_traefik_state | default('started') }}"
    recreate: "{{ docker_container_traefik_recreate | default(false) }}"
    restart: "{{ docker_container_traefik_restart | default(false) }}"
    restart_policy: "{{ docker_container_traefik_restart_policy | default('always') }}"
    container_default_behavior: no_defaults
    auto_remove: "{{ docker_container_traefik_auto_remove | default(false) }}"
    detach: "{{ docker_container_traefik_detach | default(true) }}"
    init: "{{ docker_container_traefik_init | default(false) }}"
    interactive: "{{ docker_container_traefik_interactive | default(false) }}"
    keep_volumes: "{{ docker_container_traefik_keep_volumes | default(true) }}"
    memory: "{{ docker_container_traefik_memory | default('0') }}"
    paused: "{{ docker_container_traefik_paused | default(false) }}"
    privileged: "{{ docker_container_traefik_privileged | default(false) }}"
    read_only: "{{ docker_container_traefik_read_only | default(false) }}"
    tty: "{{ docker_container_traefik_tty | default(false) }}"
    env_file: "{{ docker_container_traefik_env_file | default(omit) }}"
    env: "{{ docker_container_traefik_env | default(omit) }}"
    volumes: "{{ docker_container_traefik_volumes | default(omit) }}"
    labels: "{{ docker_container_traefik_labels | default(omit) }}"
    networks_cli_compatible: "{{ docker_container_traefik_networks_cli_compatible | default(true) }}"
    network_mode: "{{ docker_network_traefik_name }}"
    pull: "{{ docker_container_traefik_pull | default(false) }}"
    networks: "{{ docker_container_traefik_networks }}"
    published_ports: "{{ docker_container_traefik_ports | default(omit) }}"

- name: docker_container {{ docker_container_traefik_name }} - Wait until letsencrypt acme.json
  wait_for:
    path: "{{ docker_container_traefik_letsencrypt_acme_json_file }}"
    state: present
    timeout: 120
    sleep: 1
    delay: 2
  when: docker_container_traefik_letsencrypt_acme_json_wait_for
